# Generated by Django 3.0.2 on 2020-02-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('counter', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapi.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='text', to='myapi.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapi.Page'),
            preserve_default=False,
        ),
    ]
