# Generated by Django 3.0.2 on 2020-02-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200202_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='page',
        ),
        migrations.RemoveField(
            model_name='text',
            name='page',
        ),
        migrations.RemoveField(
            model_name='video',
            name='page',
        ),
    ]
