# Generated by Django 3.0.2 on 2020-02-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200202_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
