# Generated by Django 3.0.2 on 2020-02-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200202_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='page',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='myapi.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='page',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='myapi.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='page',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='myapi.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(default='Без названия', max_length=140),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='Без названия', max_length=140),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(default='Без названия', max_length=140),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='Без названия', max_length=140),
        ),
    ]
